import { readFileSync, writeFileSync } from 'node:fs';

const sourceUrl = new URL('./source/acoustic-atlas.html', import.meta.url);
const outputUrl = new URL('./index.html', import.meta.url);
const fragment = readFileSync(sourceUrl, 'utf8');

const shellStyles = [
  ':root { color-scheme: light; background: rgb(241 237 225); }',
  '* { box-sizing: border-box; }',
  'html, body { width: 100%; min-width: 320px; min-height: 100%; margin: 0; }',
  'body { min-height: 100vh; overflow-x: hidden; background: rgb(241 237 225); }',
  '#acoustic-atlas { width: 100%; min-height: 100vh; border: 0; box-shadow: none; }',
  '@media (min-width: 1100px) {',
  '  #acoustic-atlas .atlas-header { min-height: 68px; padding-inline: 28px; }',
  '  #acoustic-atlas .atlas-brand { font-size: 18px; }',
  '  #acoustic-atlas .atlas-tab { padding-inline: 14px; font-size: 11px; }',
  '  #acoustic-atlas .atlas-shell { grid-template-columns: 62px minmax(0, 1fr); }',
  '  #acoustic-atlas .atlas-rail-btn { min-height: 92px; font-size: 12px; }',
  '  #acoustic-atlas .atlas-hero { grid-template-columns: minmax(250px, .72fr) minmax(560px, 1.7fr) minmax(180px, .52fr); min-height: 590px; }',
  '  #acoustic-atlas .atlas-intro { padding: 42px 30px 28px; }',
  '  #acoustic-atlas .atlas-title { max-width: 360px; font-size: clamp(58px, 5.6vw, 92px); }',
  '  #acoustic-atlas .atlas-subtitle { max-width: 320px; font-size: 15px; }',
  '  #acoustic-atlas .atlas-spec-list { gap: 10px; }',
  '  #acoustic-atlas .atlas-spec-list li { grid-template-columns: 28px 1fr; font-size: 11px; }',
  '  #acoustic-atlas #atlas-3d { height: 500px; }',
  '  #acoustic-atlas .atlas-model-hint { right: 24px; bottom: 82px; font-size: 10px; }',
  '  #acoustic-atlas .atlas-explosion { right: 24px; bottom: 22px; left: 24px; font-size: 10px; }',
  '  #acoustic-atlas .atlas-metrics { padding: 36px 22px 24px; }',
  '  #acoustic-atlas .atlas-value { font-size: 34px; }',
  '  #acoustic-atlas .atlas-metric small { font-size: 11px; }',
  '  #acoustic-atlas .atlas-label { font-size: 9px; }',
  '  #acoustic-atlas .atlas-drawing { padding: 18px 22px; }',
  '  #acoustic-atlas .atlas-blueprint { height: 220px; }',
  '  #acoustic-atlas .atlas-drawing-head { font-size: 10px; }',
  '  #acoustic-atlas .atlas-band { min-height: 126px; }',
  '  #acoustic-atlas .atlas-band-metric { padding-inline: 28px; }',
  '  #acoustic-atlas .atlas-band-metric .atlas-value { font-size: 36px; }',
  '  #acoustic-atlas .atlas-band-metric small { font-size: 11px; }',
  '  #acoustic-atlas .atlas-detail { padding: 22px; }',
  '  #acoustic-atlas .atlas-material-stack { min-height: 190px; }',
  '  #acoustic-atlas .atlas-spectrum { height: 190px; }',
  '  #acoustic-atlas .atlas-section-head { padding: 42px 34px 28px; }',
  '  #acoustic-atlas .atlas-section-title { max-width: 780px; font-size: clamp(52px, 5vw, 82px); }',
  '  #acoustic-atlas .atlas-section-copy { max-width: 410px; font-size: 15px; }',
  '  #acoustic-atlas .atlas-theory { grid-template-columns: 280px minmax(0, 1fr); min-height: 650px; }',
  '  #acoustic-atlas .atlas-step-btn { min-height: 92px; padding: 20px; }',
  '  #acoustic-atlas .atlas-step-btn span:last-child { font-size: 14px; }',
  '  #acoustic-atlas .atlas-wave-lab { min-height: 650px; padding: 28px; }',
  '  #acoustic-atlas .atlas-wave-stage { min-height: 470px; }',
  '  #acoustic-atlas .atlas-wave-svg { height: 470px; }',
  '  #acoustic-atlas .atlas-wave-detail strong { font-size: 25px; }',
  '  #acoustic-atlas .atlas-wave-detail p { font-size: 14px; }',
  '  #acoustic-atlas .atlas-construction { min-height: 670px; grid-template-columns: minmax(0, 1.42fr) minmax(290px, .58fr); }',
  '  #acoustic-atlas .atlas-exploded-svg-wrap { padding: 28px; }',
  '  #acoustic-atlas .atlas-exploded-svg { height: 610px; }',
  '  #acoustic-atlas .atlas-layer-btn { min-height: 76px; padding: 14px 18px; }',
  '  #acoustic-atlas .atlas-layer-name { font-size: 14px; }',
  '  #acoustic-atlas .atlas-materials-layout { grid-template-columns: minmax(0, 1fr) 340px; min-height: 650px; }',
  '  #acoustic-atlas .atlas-samples { gap: 18px; padding: 28px; }',
  '  #acoustic-atlas .atlas-sample { min-height: 250px; padding: 18px; }',
  '  #acoustic-atlas .atlas-material-analysis { padding: 28px; }',
  '  #acoustic-atlas .atlas-lab-layout { grid-template-columns: minmax(0, 1.45fr) minmax(320px, .55fr); min-height: 650px; }',
  '  #acoustic-atlas .atlas-lab-plan { padding: 28px; }',
  '  #acoustic-atlas .atlas-lab-svg { height: 520px; }',
  '  #acoustic-atlas .atlas-evidence-item { padding: 22px; }',
  '  #acoustic-atlas .atlas-evidence-item strong { font-size: 18px; }',
  '  #acoustic-atlas .atlas-evidence-item p { font-size: 12px; }',
  '  #acoustic-atlas .atlas-footer { min-height: 62px; padding-inline: 24px; font-size: 10px; }',
  '}',
  '@media (min-width: 1700px) {',
  '  #acoustic-atlas .atlas-header { min-height: 76px; }',
  '  #acoustic-atlas .atlas-hero { min-height: 680px; }',
  '  #acoustic-atlas #atlas-3d { height: 580px; }',
  '  #acoustic-atlas .atlas-title { max-width: 420px; font-size: 98px; }',
  '  #acoustic-atlas .atlas-blueprint { height: 260px; }',
  '}',
  '@media (max-width: 700px) {',
  '  #acoustic-atlas { min-height: 100svh; }',
  '}'
].join('\n');

const documentHtml = [
  '<!doctype html>',
  '<html lang="ru">',
  '<head>',
  '<meta charset="utf-8">',
  '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">',
  '<meta name="theme-color" content="#f1ede1">',
  '<meta name="description" content="Интерактивный акустический атлас проекта Тихие Стены">',
  '<title>Тихие Стены — Акустический атлас</title>',
  '</head>',
  '<body>',
  fragment,
  '<style id="fullscreen-shell">',
  shellStyles,
  '</style>',
  '</body>',
  '</html>'
].join('\n');

writeFileSync(outputUrl, documentHtml, 'utf8');
console.log(outputUrl.pathname);
